// <auto-generated />
using Bookmrqr.FinanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookmrqr.FinanceService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180622114909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Bookmrqr.FinanceService.Data.ProcessedBookmark", b =>
                {
                    b.Property<string>("AggregateId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsProcessed");

                    b.HasKey("AggregateId");

                    b.ToTable("ProcessedBookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
